### ISSUE TITLE
Create app from tutorial "Tour of Heroes"

### ISSUE THREAD

**Issue by G3rmainCT** [gmendozas/angular_app#2]

**Comment by gmendozas** [comment]
App from tutorial has been finished and uploaded.
![heroes_search](https://user-images.githubusercontent.com/1510362/40454913-41cc19f8-5eb0-11e8-8c47-1de7c5546d2f.PNG)

![home_tour_of_heroes](https://user-images.githubusercontent.com/1510362/40454914-41ede952-5eb0-11e8-876d-afe033b0fe32.PNG)

![detail_hero](https://user-images.githubusercontent.com/1510362/40454915-420f7a04-5eb0-11e8-81b4-6a7cc395e14b.PNG)

![heroes](https://user-images.githubusercontent.com/1510362/40454916-423014a8-5eb0-11e8-8294-289185dc87b4.PNG)
